openapi: 3.0.1
info:
  title: MercadoTech Auth API
  version: "1.0.0"
paths:
  /login:
    post:
      summary: Gera um token JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Token gerado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '401':
          description: Credenciais inválidas
  /token/validate:
    post:
      summary: Valida um token JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidateRequest'
      responses:
        '200':
          description: Resultado da validação
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidateResponse'
components:
  schemas:
    LoginRequest:
      type: object
      properties:
        clientId:
          type: string
        clientSecret:
          type: string
      required:
        - clientId
        - clientSecret
    TokenResponse:
      type: object
      properties:
        token:
          type: string
    ValidateRequest:
      type: object
      properties:
        token:
          type: string
        clientSecret:
          type: string
      required:
        - token
        - clientSecret
    ValidateResponse:
      type: object
      properties:
        valid:
          type: boolean
