application:
    name: mercado-tech-auth
management:
  endpoints:
    web:
      exposure:
        include: "prometheus,metrics"
  metrics:
    tags:
      application: mercado-tech-auth
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
      percentiles:
        http:
          server:
            requests: 0.5,0.95,0.99
LOG_PATTERN: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
POD_NAME: "mercadotech-auth-server"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
