management:
  endpoints:
    web:
      exposure:
        include: "prometheus,metrics"
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
      percentiles:
        http:
          server:
            requests: 0.5,0.95,0.99
LOG_PATTERN: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
POD_NAME: "mercadotech-auth-server"
